APP:
  ENVIRONMENT: test
  DEBUG: True

DATABASE:
  USERNAME: user
  PASSWORD: password
  HOST: host.net
  PORT: 4532
  DB: database

S3:
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  BUCKET: BUCKET